extraction:
  cpp:
    after_prepare: 
      - python report.py 103
  cobol:
    after_prepare: 
      - python report.py 103
  csharp:
    after_prepare: 
      - python report.py 103
  java:
    after_prepare: 
      - python report.py 103
  javascript:
    after_prepare: 
      - python report.py 103
  python:
    after_prepare: 
      - python report.py 103
